name: Push-to-EC2

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Deploy files to EC2 instance using SSH
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Execute remote commands to rebuild and restart Next.js app
      - name: Execute SSH commands to rebuild and restart Next.js app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Go to the Next.js project directory
            cd ${{ secrets.TARGET_DIR }}

            # Stop any running Next.js process
            pkill -f "npm run dev" || true

            # Pull the latest code
            git pull origin main

            # Install dependencies
            npm install

            # Build the Next.js project
            npm run build

            # Restart the Next.js dev server
            nohup npm run dev > dev.log 2>&1 &
